name: Android Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Remove Gradle cache
      run: |
        rm -rf ~/.gradle/caches/
        rm -rf ~/.gradle/daemon/
        rm -rf ~/.gradle/native/

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permission to Gradle
      run: chmod +x ./gradlew

    - name: Clean project
      run: ./gradlew clean

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
