name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Debug APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        build-tools-version: "34.0.0"
        ndk-version: "25.2.9519653"
        cmake-version: "3.22.1"

    - name: Grant execute permission to Gradle
      run: chmod +x ./gradlew

    - name: Clean and regenerate Gradle config
      run: |
        rm -rf ~/.gradle/caches/
        rm -rf ~/.gradle/wrapper/
        rm -rf .gradle
        ./gradlew --stop
        
    - name: Force Gradle plugin resolution
      run: |
        echo "systemProp.gradle.unsafe.configuration.on.demand=true" >> gradle.properties
        echo "android.suppressUnsupportedCompileSdk=35" >> gradle.properties
        echo "org.gradle.parallel=true" >> gradle.properties

    - name: Build with debug info
      run: ./gradlew assembleDebug --stacktrace --scan --no-daemon

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
